### ISSUE TITLE
npm install fails with error

### ISSUE THREAD

**Issue by detj** [BrandwatchLtd/remimi#15]
I cloned the repo and ran `npm install` with node@8.4.0, here are the logs

```
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated conventional-changelog@0.0.17: Please update conventional-changelog to >1.0.0. If you are running the cli, use conventional-changelog-cli
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> fsevents@1.1.2 install /Users/detj/src/remimi/node_modules/fsevents
> node install

[fsevents] Success: "/Users/detj/src/remimi/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> remimi@0.0.0-development prepublish /Users/detj/src/remimi
> npm run test && npm run lint && npm run build


> remimi@0.0.0-development test /Users/detj/src/remimi
> mocha --compilers js:babel-core/register -r jsdom-global/register



  mixpanelMiddleware
    ✓ initialises with the given token
    ✓ initialises with the given config
    middleware function
      ✓ does not attempt to track an action with no meta
      ✓ does not attempt to track an action with no mixpanel meta
      ✓ tracks a mixpanel event with the given event name
      ✓ tracks a mixpanel event with the action name as action property
      ✓ tracks an action with a mixpanel event with props
      ✓ tracks an action with action type override
      ✓ tracks an increment event with the provided values
      ✓ tracks timed event with the provided event name
      with user data
        ✓ adds user data to the request
    middleware formatters
      action type
        ✓ uses default identity formatter
        ✓ formats the event type
      properties
        ✓ uses default identity formatter
        ✓ formats all properties of payload
        ✓ formats all values of payload
        ✓ formats all properties and values of payload
        ✓ formats the increment name


  18 passing (215ms)


> remimi@0.0.0-development lint /Users/detj/src/remimi
> eslint src/**


> remimi@0.0.0-development build /Users/detj/src/remimi
> rm -rf dist && mkdir dist && babel src --out-dir dist

Error: Plugin 20 specified in "/Users/detj/src/remimi/node_modules/babel-preset-es2015/index.js" provided an invalid property of "name"
    at Plugin.init (/Users/detj/src/remimi/node_modules/babel-core/lib/transformation/plugin.js:138:13)
    at Function.normalisePlugin (/Users/detj/src/remimi/node_modules/babel-core/lib/transformation/file/options/option-manager.js:147:12)
    at /Users/detj/src/remimi/node_modules/babel-core/lib/transformation/file/options/option-manager.js:181:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/detj/src/remimi/node_modules/babel-core/lib/transformation/file/options/option-manager.js:153:20)
    at OptionManager.mergeOptions (/Users/detj/src/remimi/node_modules/babel-core/lib/transformation/file/options/option-manager.js:245:36)
    at /Users/detj/src/remimi/node_modules/babel-core/lib/transformation/file/options/option-manager.js:289:14
    at /Users/detj/src/remimi/node_modules/babel-core/lib/transformation/file/options/option-manager.js:310:24
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/detj/src/remimi/node_modules/babel-core/lib/transformation/file/options/option-manager.js:305:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! remimi@0.0.0-development build: `rm -rf dist && mkdir dist && babel src --out-dir dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the remimi@0.0.0-development build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/detj/.npm/_logs/2017-08-17T16_01_51_797Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! remimi@0.0.0-development prepublish: `npm run test && npm run lint && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the remimi@0.0.0-development prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/detj/.npm/_logs/2017-08-17T16_01_51_873Z-debug.log
```

I'm not sure why running npm install is also running `npm run test` and `npm run build`. I don't see any `post-install` script. What am I missing?

Also, there a couple of deprecated package warnings too. I'm trying to clone the project and try out a few things on it and maybe will add more tests and send a PR too.

**Comment by detj** [comment]
`npm prepublish` has been deprecated too as of *npm@5.x.x`.

**Comment by detj** [comment]
You're right @HHogg. I removed my global `babel-cli` and the error went with it too. :)

**Comment by HHogg** [comment]
Great stuff :) I'll close this issue as I don't think the conflict of global and local modules is down to this package.
